### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lgcambero** [rscmbbng/Border-Check#1]
I can not run the tool. I get the following error: Any ideas?
![screenshot from 2016-02-27 16-54-47](https://cloud.githubusercontent.com/assets/11602705/13374984/eb648598-dd72-11e5-97a1-4b65b70cbea1.png)

**Comment by epsylon** [comment]
It looks a problem on your proxy. Do you have any?. 

BC uses a webserver launched at: 127.0.0.1, port 8080. You should check that you are allowing access to that place from your shell, correctly.
